[package]
name = "sc2exe"
version = "0.1.0"
edition = "2021"
description = "Convert shellcode to executable for debugging (cross-platform)"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
scroll = "0.12"

[profile.release]
opt-level = "z"
lto = true
strip = true